### ISSUE TITLE
Link author format

### ISSUE THREAD

**Issue by mariusc** [iOS-Goodies/Contributing-Guidelines#2]
The guidelines say that an article link should follow this format: 
`[Title of the Article](link), by [Name of the Author](link-for-twitter)`. 
But lately, I've seen that almost all the article links are formatted as
 `[Title of the Article](link), by [@twitter_username](link-for-twitter)`. 

Should we update the contributing guidelines to use the twitter username of the author, instead of his name? Or should we keep it like this and enforce this guideline a bit more?

**Comment by mariusc** [comment]
Any opinions on this one?

**Comment by dkhamsing** [comment]
Should be `[Name of the Author](link-for-twitter)` but the other alternative is also acceptable..

**Comment by mariusc** [comment]
I think it would be better to use the same format for all articles. It looks a bit messy if some use the full name of the author and some use the twitter username. Personally, I like it more with the full name of the author than with the twitter username, but it's not a matter of my personal taste, it's about having them all look the same. Should we decide on one of the two and try to enforce it a bit more form now on?

**Comment by mariusc** [comment]
I made a PR to update the contributing guidelines and change the author format to use his twitter username, since that seems to be the most popular way lately :). https://github.com/iOS-Goodies/Contributing-Guidelines/pull/3
